on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    - build
name: Semgrep
jobs:
  semgrep:
    name: Scan 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        config: s/d2WE
        publishToken: ${{ secrets.dc89cccc1cf9f8bf9fc6c1c1c18981843d0dc9e61d9ef070f7ace9eab5ddf58e }}
